- name: Enable Universe
  when: ansible_distribution|lower == 'ubuntu'
  ansible.builtin.import_tasks: pkgs/ubuntu.yml

- name: Install nginx
  when: ansible_os_family|lower == 'debian'
  ansible.builtin.import_tasks: nginx/debian.yml

- name: Get TLS Certificate
  when: certbot_enabled|bool
  ansible.builtin.include_role:
    name: geerlingguy.certbot

- name: Install Jitsi
  when: ansible_os_family|lower == 'debian'
  ansible.builtin.import_tasks: jitsi/debian.yml

- name: Configure Jitsi
  when: managed_jitsi_config|bool
  ansible.builtin.import_tasks: jitsi/config.yml

- name: Update nginx configuration for Certbot
  when: (certbot_enabled|bool) and (ansible_os_family|lower == 'debian')
  ansible.builtin.import_tasks: certbot/debian.yml
