- name: Ensure universe
  ansible.builtin.apt_repository:
    repo: deb {{ apt_mirror }} {{ ansible_distribution_release }} universe
    state: present
    update_cache: false
    filename: universe
- name: Ensure universe-updates
  ansible.builtin.apt_repository:
    repo: deb {{ apt_mirror }} {{ ansible_distribution_release }}-updates universe
    state: present
    update_cache: false
    filename: universe
- name: Ensure universe-security
  ansible.builtin.apt_repository:
    repo: deb {{ apt_mirror }} {{ ansible_distribution_release }}-security universe
    state: present
    update_cache: false
    filename: universe
