- name: Update vhost
  ansible.builtin.template:
    src: nginx-vhost.conf.j2
    dest: /etc/nginx/sites-available/{{ jitsi_domain }}.conf
    mode: "644"
  notify:
    - Restart nginx

- name: Ensuring our nginx configuration is enabled
  ansible.builtin.file:
    src: /etc/nginx/sites-available/{{ jitsi_domain }}.conf
    dest: /etc/nginx/sites-enabled/{{ jitsi_domain }}.conf
    owner: root
    group: root
    mode: 644
    state: link
  notify:
    - Restart nginx

- name: Ensuring our the old nginx configuration is disabled
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/localhost.conf
    state: absent
  notify:
    - Restart nginx
